[2024-05-20T19:10:41.507+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T19:10:41.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_book_dag.get_title_operator manual__2024-05-20T19:05:22.802141+00:00 [queued]>
[2024-05-20T19:10:41.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_book_dag.get_title_operator manual__2024-05-20T19:05:22.802141+00:00 [queued]>
[2024-05-20T19:10:41.594+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-20T19:10:41.627+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_title_operator> on 2024-05-20 19:05:22.802141+00:00
[2024-05-20T19:10:41.643+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=232) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T19:10:41.647+0000] {standard_task_runner.py:63} INFO - Started process 234 to run task
[2024-05-20T19:10:41.658+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_book_dag', 'get_title_operator', 'manual__2024-05-20T19:05:22.802141+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/get_book_dag.py', '--cfg-path', '/tmp/tmpgqlx0pyc']
[2024-05-20T19:10:41.661+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask get_title_operator
[2024-05-20T19:10:41.804+0000] {task_command.py:426} INFO - Running <TaskInstance: get_book_dag.get_title_operator manual__2024-05-20T19:05:22.802141+00:00 [running]> on host 60554ca90225
[2024-05-20T19:10:42.019+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_book_dag' AIRFLOW_CTX_TASK_ID='get_title_operator' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T19:05:22.802141+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T19:05:22.802141+00:00'
[2024-05-20T19:10:42.023+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T19:10:42.089+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T19:10:42.091+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_book_dag.py", line 28, in get_title_func
    book_title = soup_content.select_one('table h1').text.split('::')[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'select_one'
[2024-05-20T19:10:42.136+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=get_book_dag, task_id=get_title_operator, run_id=manual__2024-05-20T19:05:22.802141+00:00, execution_date=20240520T190522, start_date=20240520T191041, end_date=20240520T191042
[2024-05-20T19:10:42.176+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task get_title_operator ('tuple' object has no attribute 'select_one'; 234)
[2024-05-20T19:10:42.206+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T19:10:42.285+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T19:10:42.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
